theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

site_name: CnC Tools and Resources
site_description: A series of resources for mappers and linux users for WW 2.5D games
site_url: https://cattanker.github.io/CnC-Resource-Docs/
repo_url: https://github.com/CatTanker/cnc_map_tool_guide
nav:
  - Home: index.md
  - Tools: tools.md
  - Map Resources: resources.md
  - Linux: linux.md
