site_name: CnC Tools and Resources
site_url: https://example.com/
nav:
  - Home: index.md
  - About: about.md
  - Tools: tools.md
  - Map Resources: resources.md
  - Linux: linux.md
theme: readthedocs
